[package]
authors = ["Chiu-Hsiang Hsu <wdv4758h@gmail.com>"]
name = "pycontw"
version = "0.1.0"

[lib]
name = "pycontw"
crate-type = ["cdylib"]

[dependencies]
cpython = { version = "0.1.0", features = ["extension-module"] }
lazy_static = "0.2.8"
brotli = "1.0.8"

[profile.release]
lto = true
